version: "3"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  golang_seed:
    build: ./db/
    tty: true 
    volumes:
      - ./:/go/src/app
    depends_on:
      - mysql
