name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: check
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest

    - name: Test code
      run: go test ./problem/...
